name: auto report back

on:
  # 定时器触发：
  schedule:
    # 每天的22:47执行（UTC时间，另外GitHub Actions出现延后是正常的）
    - cron: '47 14 * * *'
  # 手动触发：
  workflow_dispatch:

jobs:
  report_back:
    runs-on: ubuntu-latest
    env:
      ID: ${{ secrets.ID }}
      PASSWORD: ${{ secrets.PASSWORD }}
      IS_UG: ${{ secrets.IS_UG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r ./requirements.txt
      - name: Report back
        run: python ./report_back.py
